{{- if or .Values.ui.ingress.enabled .Values.ingestion.ingress.enabled }}
{{- $name := include "seq.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $name }}
  labels:
    app: {{ template "seq.name" . }}
    chart: {{ template "seq.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.ingress.labels }}
{{ toYaml .Values.ingress.labels | indent 4 }}
{{- end }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
{{- range .Values.ingress.tls }}
    - hosts:
{{- range .hosts }}
        - {{ . | quote }}
{{- end }}
      secretName: {{ .secretName }}
{{- end }}
{{- end }}
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className | quote }}
  {{- end }}
  rules:
{{- if .Values.ui.ingress.enabled }}
{{- $uiPath := .Values.ui.ingress.path -}}
{{- $uiPort := .Values.ui.service.port -}}
{{- range .Values.ui.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $uiPath }}
            pathType: Prefix
            backend:
              service:
                name: {{ $name }}
                port:
                  number: {{ $uiPort }}
{{- end }}
{{- end }}
{{- if .Values.ingestion.ingress.enabled }}
{{- $ingestionPath := .Values.ingestion.ingress.path -}}
{{- $ingestionPort := .Values.ingestion.service.port -}}
{{- range .Values.ingestion.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $ingestionPath }}
            pathType: Prefix
            backend:
              service:
                name: {{ $name }}
                port:
                  number: {{ $ingestionPort }}
{{- end }}
{{- end }}
{{- end }}
